- Python 3 doesn't have the `unicode` method except if we're using six - we should return the response for submitting feedback and it's currently missing
````
TypeError: The view function for 'api.feedback_method' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [25/Feb/2023 08:17:57] "POST /api/quizzes/feedback/gcp HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/home/student_02_ca471c0755bd/venvs/developingapps/lib/python3.9/site-packages/flask/app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'api.feedback_method' did not return a valid response. The function either returned None or ended without a return statement.
```