k8s Lab and Video needs below correction
Lab - https://www.cloudskillsboost.google/course_sessions/812316/labs/190664
Video - https://www.cloudskillsboost.google/course_sessions/812316/video/190665
Course - https://www.cloudskillsboost.google/course_templates/2

In the Lab, Task 4 needs the correction.
Currently, the Task 4 is expected to fail but as below.

Expected -
```
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/qwiklabs-gcp-04-9d788c36b0e6/quickstart-image" failed: step exited with non-zero status: 1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 1 "gcr.io/qwiklabs-gcp-04-9d788c36b0e6/quickstart-image" failed: step exited with non-zero status: 1
```

The Task 4 is incorrectly failing due to the incorrect argument passed
to the cloudbuild.yaml
The arguments only contains the ['fail'] instead of the
['/quickstart.sh', 'fail']
As there is no mention of ENTRYPOINT in Dockerfile as well as in
cloudbuild.yaml, the passed arguments overrides the CMD in the
Dockerfile[1].

I have also updated the executable bit of all the quickstart.sh

As a suggestion in the Lab, I think it would have been more appropriate
if after building and pushing the images to gcr.io, the Lab also teach
about how to pull and run the images using docker command.

References -

[1]: 4th Point of https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact